version: "3"

services:
  postgres_db:
    image: postgres:15.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TESTING: 1
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
      - DB_URL_PV=postgresql://postgres:postgres@postgres_db:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
    command: >
      bash -c "pytest --cov=./src
      && coverage report -m
      && coverage xml
      && cp .coverage ./src/tests/
      && cp coverage.xml ./src/tests/"
    depends_on:
      - postgres_db
    volumes:
      - ./src/:/app/src
