version: "3"

services:
  postgres_db:
    image: postgres:15.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TESTING: 1
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
      - DB_URL_PV=postgresql://postgres:postgres@postgres_db:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
      - DELETE_CACHE_TIME_SECONDS=0
      - CACHE_TIME_SECONDS=0
      - N_SLOW_CALLS_PER_MINUTE=20
    command: >
      bash -c "pytest --cov=./nowcasting_api
      && coverage report -m
      && coverage xml
      && cp .coverage ./nowcasting_api/tests/
      && cp coverage.xml ./nowcasting_api/tests/"
    depends_on:
      - postgres_db
    volumes:
      - ./nowcasting_api/:/app/nowcasting_api
